my_blog/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.user_login, name='user_login')
]

my_blog/article/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('tag/<int:tag_pk>', views.articles_with_tag, name="articles_with_tag"),

]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('account/', include('account.urls', namespace='account')),
    path('tz_detect/', include('tz_detect.urls')),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('comment/', include('comments.urls'))
]

my_blog/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Tag(models.Model):
    tag_name = models.CharField(max_length=20)

    def __str__(self):
        return self.tag_name

class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.objects.id])

    def read_number(self):
        return self.readnum.read_num


class ReadNum(models.Model):
    read_num = models.IntegerField(default=0)
    articlepost = models.OneToOneField(ArticlePost, on_delete=models.CASCADE)

my_blog/article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator
from django.db.models import Count
from article.models import ArticlePost, Tag, ReadNum
from comments.models import Comment
from comments.forms import CommentForm
import markdown




# Create your views here.


def article_list(request):
    page = request.GET.get('page' , 1)
    articles = ArticlePost.objects.all()
    paginator = Paginator(articles, 10)
    articles = paginator.get_page(page)
    cur_num = articles.number
    page_range = list(range(max(cur_num - 2, 1), min(cur_num + 2, articles.paginator.num_pages) + 1))

    if cur_num - 2 > 2:
        page_range.insert(0, '...')
        page_range.insert(0, 1)
    elif cur_num - 2 == 2:
        page_range.insert(0, 1)

    if cur_num + 2 < paginator.num_pages - 1:
        page_range.append('...')
        page_range.append(paginator.num_pages)
    elif cur_num + 2 == paginator.num_pages - 1:
        page_range.append(paginator.num_pages)
    context = {}
    context['articles'] = articles
    context['tags'] = Tag.objects.annotate(article_count=Count('articlepost'))
    context['page_range'] = page_range
    return render(request, 'article/list.html', context)

def article_detail(request, id):
    context = {}
    article = get_object_or_404(ArticlePost, pk=id)
    if not request.COOKIES.get("read_%s" % id):
        if ReadNum.objects.filter(articlepost=article).count():
            readnum = ReadNum.objects.get(articlepost=article)
        else:
            readnum = ReadNum(articlepost=article)
        readnum.read_num += 1
        readnum.save()
    article.save()
    article.body = markdown.markdown(article.body, extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
    ])
    article_content_type = ContentType.objects.get_for_model(article)
    context['next_article'] = ArticlePost.objects.filter(created__gt=article.created).last()
    context['previous_article'] = ArticlePost.objects.filter(created__lt=article.created).first()
    context['article'] = article
    context['read'] = article.read_number
    context['comment_count'] = Comment.objects.filter(content_type=article_content_type, object_id=id).count()
    response = render(request, "article/detail.html", context)
    response.set_cookie("read_%s" % article.id, "true")
    return response

def articles_with_tag(request, tag_pk):
    tag = get_object_or_404(Tag, pk=tag_pk)
    page = request.GET.get('page', 1)
    articles = ArticlePost.objects.filter(tag=tag)
    paginator = Paginator(articles, 10)
    articles = paginator.get_page(page)
    cur_num = articles.number
    page_range = list(range(max(cur_num - 2, 1), min(cur_num + 2, articles.paginator.num_pages) + 1))

    if cur_num - 2 > 2:
        page_range.insert(0, '...')
        page_range.insert(0, 1)
    elif cur_num - 2 == 2:
        page_range.insert(0, 1)

    if cur_num + 2 < paginator.num_pages - 1:
        page_range.append('...')
        page_range.append(paginator.num_pages)
    elif cur_num + 2 == paginator.num_pages - 1:
        page_range.append(paginator.num_pages)
    context = {}
    context['tag'] = tag
    context['articles'] = articles
    context['tags'] = Tag.objects.annotate(article_count=Count('articlepost'))
    context['page_range'] = page_range
    return render(request, 'article/tag_list.html', context)

my_blog/templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load comment_tags %}
{%block title%}
    {{article.title}}
{% endblock title%}
{% block header_extends %}
    <link rel="stylesheet" href="{% static 'article/article_list.css' %}">
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock header_extends %}
{% block article_active %}active{%endblock%}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-12 col-xs--12 col-xs-offset-1">
            <h3>{{ article.title }}</h3>
            <ul class="article-info-description">
                <li>Author: {{article.author}}</li>
                <li>Created at: {{article.created | date:"m/d/Y G:n:s"}}</li>
                <li>Type: <a href="{% url 'article:articles_with_tag' article.tag.pk%}">{{ article.tag }}</a></li>
                <li>Read({{read}})</li>
                <li>Comment:({% get_comment_count article %})</li>
            </ul>
            <div class="shadow-sm p-3 mb-2 bg-white rounded">
                <p>{{article.body|safe}}</p>
            </div>
            <hr>
            <ul class="pager">
                {% if previous_article is None %}
                    <li>Prev: No more previous article</li>
                {% else %}
                    <li>Prev: <a href="{% url 'article:article_detail' previous_article.pk%}">{{previous_article.title}}</a></li>
                {% endif %}
                {% if next_article is None %}
                    <li>Next: No more next article</li>
                {% else %}
                    <li>Next: <a href="{% url 'article:article_detail' next_article.pk%}">{{next_article.title}}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="comment-area">
                <h3 class="comment-area-title">Submit Comment</h3>
                {% if user.is_authenticated %}
                    <form id="comment_form" action="{% url 'update_comment' %}" method="POST" style="overflow:hidden">
                        <label>{{ user.username }} login successfully. Welcome to comment~</label>
                        <div id="reply_content_container" style="display:none;">
                                <p id="reply_title">Reply to：</p>
                                <div id="reply_content"></div>
                        </div>
                        {% csrf_token %}
                        {% get_comment_form article as comment_form %}
                        {% for field in comment_form %}
                            {{field}}
                        {% endfor %}
                        <span id="comment_error" class="text-danger pull-left"></span>
                        <br>
                        <input type="submit" class="btn btn-primary">
                    </form>
                {% else %}
                    Need to login to comment
                    <a class="btn btn-primary" href="{% url 'login' %}?from={{ request.get_full_path }}">Login</a>
                    <span> or </span>
                    <a class="btn btn-danger" href="{% url 'register' %}?from={{ request.get_full_path }}">Register</a>
                {% endif %}
            </div>
            <div class="comment-area">
                <h3 class="comment-area-title">Comment List</h3>
                <div id="comment_list">
                    {% get_comment_list article as comments %}
                    {% for comment in comments %}
                        <div id="root_{{ comment.pk }}" class="comment">
                            <span>{{comment.user.username}}</span>
                            <span>{{comment.comment_time|date:"Y-m-d H:i:s"}}</span>
                            <div id="comment_{{comment.pk}}">
                                {{comment.text|safe}}
                            </div>
                            <a href="javascript:reply({{ comment.pk }});">Reply</a>

                            {% for reply in comment.root_comment.all %}
                                <div class="reply">
                                    <span>{{ reply.user.username }}</span>
                                    <span>({{ reply.comment_time|date:"Y-m-d H:i:s" }})</span>
                                    <span>Reply</span>
                                    <span>{{ reply.reply_to.username }}：</span>
                                    <div id="comment_{{ reply.pk }}">
                                        {{ reply.text|safe }}
                                    </div>
                                    <a href="javascript:reply({{ reply.pk }});">Reply</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% empty %}
                        No Comment
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

{% block script_extends%}
    <script type="text/javascript">
        function numFormat(num){
            return ('00' + num).substr(-2);
        }
        function timeFormat(timestamp){
            var datetime = new Date(timestamp * 1000);
            var year = numFormat(datetime.getFullYear());
            var month = numFormat(datetime.getMonth() + 1);
            var day = numFormat(datetime.getDate());
            var hour = numFormat(datetime.getHours());
            var minute = numFormat(datetime.getMinutes());
            var second = numFormat(datetime.getSeconds());
            return year + '-' + month + '-' + day + ' ' + hour + ':' + minute + ':' + second;
        }
        $("#comment_form").submit(function(){
            // 判断是否为空
            $("#comment_error").text('');
            if(CKEDITOR.instances["id_text"].document.getBody().getText().trim()==''){
                $("#comment_error").text('评论内容不能为空');
                return false;
            }
            // 更新数据到textarea
            CKEDITOR.instances['id_text'].updateElement();
            // 异步提交
            $.ajax({
                url: "{% url 'update_comment' %}",
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                success: function(data){
                    console.log(data);
                    if(data['status']=="SUCCESS"){
                        // 插入数据
                        if($('#reply_comment_id').val()=='0'){
                            // 插入评论
                            console.log(data['comment_time'])
                            console.log(timeFormat(data['comment_time']))
                            var comment_html = '<div id="root_' + data['pk'] + '" class="comment"><span>' + data['username'] + '</span><span> (' + timeFormat(data['comment_time']) + ')：</span><div id="comment_' + data['pk'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['pk'] + ');">回复</a></div>';
                            $("#comment_list").prepend(comment_html);
                        }else{
                            // 插入回复
                            var reply_html ='<div class="reply"><span>' + data['username'] + '</span><span> (' + timeFormat(data['comment_time']) + ')</span><span> Reply </span><span>' + data['reply_to'] + '：</span><div id="comment_' + data['pk'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['pk'] + ');">回复</a></div>';
                            $("#root_" + data['root_pk']).append(reply_html);
                        }
                        // 清空编辑框的内容
                        CKEDITOR.instances['id_text'].setData('');
                        $('#reply_content_container').hide();
                        $('#reply_comment_id').val('0');
                        $('#no_comment').remove();
                        $("#comment_error").text('Successfully comment!');
                    }else{
                        // 显示错误信息
                        $("#comment_error").text(data['message']);
                    }
                },
                error: function(xhr){
                    console.log(xhr);
                }
            });
            return false;
        });
        function reply(reply_comment_id){
            // 设置值
            $('#reply_comment_id').val(reply_comment_id);
            var html = $("#comment_" + reply_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();
            $('html').animate({scrollTop: $('#comment_form').offset().top - 60}, 300, function(){
                CKEDITOR.instances['id_text'].focus();
            });
        }
    </script>
{% endblock %}

my_blog/templates/article/list.html
{% extends "base.html"%}
{% load staticfiles %}
{% load comment_tags %}

{% block title %}
Index
{% endblock title %}
{% block header_extends %}
    <link rel="stylesheet" href="{% static 'article/article_list.css' %}">
{% endblock header_extends %}
{% block article_active %}active{%endblock article_active%}
{%block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-8 col-sm-8">
                <div class="card shadow p-3 mb-5 bg-white rounded">
                    <div class="card-header">
                        {% block blog_list_title %}Article List（Total {{ articles.paginator.count }} articles）{% endblock %}
                    </div>
                    <div class="card-body">
                        {% for article in articles.object_list %}
                            <div class="blog">
                                <h3><a href="{% url 'article:article_detail' article.id %}">{{ article.title}}</a></h3>
                                <p class="blog-info">
                                    <img src="{% static 'image/tags.svg'%}" width="15" height="15"><a href="{% url 'article:articles_with_tag' article.tag.pk %}">{{ article.tag }}</a>
                                    <img src="{% static 'image/clock.svg'%}" width="15" height="15">{{ article.created|date:"Y-m-d G:n:s" }}
                                    Comments:({%  get_comment_count article %})
                                </p>
                                <p>{{ article.body|striptags|truncatewords:100 | safe}}...</p>
                                <hr>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <br>
                <nav aria-label="Page navigation example">
                  <ul class="pagination">
                    <li class="page-item">
                        {% if articles.has_previous %}
                          <a class="page-link" href="?page={{articles.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                          </a>
                        {% else %}
                          <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                          </a>
                        {% endif %}
                    </li>
                    {% for page_num in page_range %}
                        {% if page_num == articles.number %}
                            <li class="page-item active"><a class="page-link" href="#">{{page_num}}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{page_num}}">{{page_num}}</a></li>
                        {% endif %}
                    {% endfor %}
                    <li class="page-item">
                      {% if articles.has_next %}
                          <a class="page-link" href="?page={{articles.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                          </a>
                        {% else %}
                          <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                          </a>
                        {% endif %}
                    </li>
                  </ul>
                </nav>
            </div>
            <div class="hidden-xs col-md-4 col-sm-4">
                <div class="card shadow p-3 mb-5 bg-white rounded">
                    <div class="card-header">
                        Article Tags
                    </div>
                    <div class="card-body">
                        <ul>
                            {%for tag in tags%}
                            <li>
                                <a href="{% url 'article:articles_with_tag' tag.pk%}">{{tag.tag_name}}</a>({{tag.article_count}})
                            </li>
                            {% empty %}
                            <li>No Tags</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{%endblock content %}

my_blog/templates/article/tag_list.html
{%extends 'article/list.html'%}
{%block title%}{{article_tag.tag_name}}{% endblock %}
{% block blog_list_title %}
    Tag：{{ article.tag }}（Total {{ articles|length }} articles）
    <a href="{% url 'article:article_list' %}">All articles</a>
{% endblock %}